package com.namma.homestay.models

import com.google.firebase.Timestamp
import com.google.firebase.firestore.PropertyName
import java.util.Date

data class Location(
    val address: String = "",
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val placeId: String = ""
)

data class Attraction(
    val name: String = "",
    val description: String = "",
    val type: String = "",
    val distance: Double = 0.0
)

data class ListingImage(
    val url: String = "",
    val type: String = "general",
    val description: String = "",
    val category: String = ""
)

data class Listing(
    val id: String = "",
    val name: String = "",
    val hostId: String = "",
    val description: String = "",
    val price: Double = 0.0,
    val coverPhoto: String = "",
    val images: List<ListingImage> = emptyList(),
    val location: Location = Location(),
    val amenities: List<String> = emptyList(),
    val rooms: List<Room> = emptyList(),
    val occupancyStatus: String = "available",
    val verificationChecklist: Map<String, Boolean> = emptyMap(),
    val localAttractions: List<Attraction> = emptyList(),
    val roomDetails: String = "",
    val hostingModel: String = "entire_home",
    val createdAt: Any? = System.currentTimeMillis(),
    val updatedAt: Any? = System.currentTimeMillis()
)

data class Room(
    val id: String = "",
    val name: String = "",
    val type: String = "bedroom_attached",
    val capacity: Int = 2,
    val price: Double = 0.0,
    val amenities: List<String> = emptyList(),
    val status: String = "available",
    val images: List<ListingImage> = emptyList(),
    val washroomImages: List<ListingImage> = emptyList(),
    val description: String = "",
    val blockedDates: List<String> = emptyList()
)

data class Inquiry(
    val id: String = "",
    val travelerId: String = "",
    val travelerName: String = "",
    val hostId: String = "",
    val listingId: String = "",
    val listingName: String = "",
    val listingImage: String = "",
    val checkIn: String = "",
    val checkOut: String = "",
    val guests: Int = 1,
    val message: String = "",
    val selectedRoomIds: List<String> = emptyList(),
    val totalPrice: Double = 0.0,
    val status: String = "sent",
    val createdAt: Any? = System.currentTimeMillis(),
    val updatedAt: Any? = System.currentTimeMillis(),
    val contactNumber: String = "",
    val read: Boolean = false,
    val lastMessage: String = ""
)

data class ChatMessage(
    val id: String = "",
    val senderId: String = "",
    val senderRole: String = "",
    val text: String = "",
    val isAutoGenerated: Boolean = false,
    val createdAt: Any? = 0
)

data class Dish(
    val name: String = "",
    val description: String = "",
    val category: String = "Breakfast",
    val imageUrl: String? = null,
    val price: Double = 0.0,
    @get:PropertyName("isSpicy")
    val isSpicy: Boolean = false,
    @get:PropertyName("isVeg")
    val isVeg: Boolean = true,
    @get:PropertyName("veg")
    val veg: Boolean = true, // Added for UI compatibility
    @get:PropertyName("spicy")
    val spicy: Boolean = false // Added for UI compatibility
)

data class Menu(
    val id: String = "",
    val listingId: String = "",
    val hostId: String = "",
    val date: String = "",
    val dishes: List<Dish> = emptyList(),
    val createdAt: Any? = System.currentTimeMillis(),
    val updatedAt: Any? = System.currentTimeMillis()
)

data class UserProfile(
    val uid: String = "",
    val name: String = "",
    val email: String = "",
    val role: String = "traveler",
    val profilePhoto: String = "",
    val contactNumber: String = "",
    val languagePreference: String = "English",
    val createdAt: Any? = System.currentTimeMillis(),
    val updatedAt: Any? = System.currentTimeMillis()
)

data class WishlistItem(
    val id: String = "",
    val travelerId: String = "",
    val listingId: String = "",
    val createdAt: Any? = System.currentTimeMillis(),
    val updatedAt: Any? = System.currentTimeMillis()
)

fun Any?.toTimestamp(): Long {
    return when (this) {
        is Number -> this.toLong()
        is String -> this.toLongOrNull() ?: 0L
        is Timestamp -> this.toDate().time
        is Date -> this.time
        else -> 0L
    }
}

